//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUBGbay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageID { get; set; }
        public int ClassifiedID { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageContent { get; set; }
    
        public virtual Classified Classified { get; set; }
    }
}
